# todos os seletores estao mapeados e centralizados neste arquivo para facilitar a leitura do codigo main, bem como a manutenção do codigo.
usernameField = '[data-test="username"]'
passwordField = '[data-test="password"]'
loginButton = '[data-test="login-button"]'
aboutButton = '[id="react-burger-menu-btn"]'
closeButton = '[id="react-burger-cross-btn"]'
addToCartBackpack = '[data-test="add-to-cart-sauce-labs-backpack"]'
addToCartBikeLight = '[data-test="add-to-cart-sauce-labs-bike-light"]'
cartLink = '[data-test="shopping-cart-link"]'
checkoutButton = '[data-test="checkout"]'
firstNameField = '[data-test="firstName"]'
lastNameField = '[data-test="lastName"]'
postalCodeField = '[data-test="postalCode"]'
continueButton = '[data-test="continue"]'
finishButton = '[data-test="finish"]'
